### ISSUE TITLE
[BUG] Library doesn't work at all

### ISSUE THREAD

**Issue by ZiraiMode** [brightec/KBarcode#38]
**Describe the bug**
Current version of library doesnt work because it uses old dependecies that will throw exception on build

```
Duplicate class com.google.android.gms.internal.vision.zze found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzf found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzg found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzh found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzi found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzv found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
Duplicate class com.google.android.gms.internal.vision.zzw found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)

Go to the documentation to learn how to Fix dependency resolution errors.

```

If you manually add newest version of `play-services-vision`  then you will get runtime crash on library init 

```
E/AndroidRuntime: FATAL EXCEPTION: FirebaseMLHandler
    Process: com.p1ng2win.gabiapplication, PID: 7373
    java.lang.VerifyError: Superclass com.google.firebase.ml.vision.barcode.internal.zzj of com.google.firebase.ml.vision.barcode.BarcodeDetectorCreator is declared final (declaration of 'com.google.firebase.ml.vision.barcode.BarcodeDetectorCreator' appears in /data/app/com.p1ng2win.gabiapplication-KiY0_DnxVctfCKFLF5qfYg==/base.apk!classes2.dex)
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.dynamite.DynamiteModule.instantiate(com.google.android.gms:play-services-basement@@17.3.0:257)
        at com.google.firebase.ml.vision.barcode.internal.zzc.zzqu(com.google.firebase:firebase-ml-vision@@24.1.0:25)
        at com.google.firebase.ml.vision.barcode.internal.zzc.zzow(com.google.firebase:firebase-ml-vision@@24.1.0:10)
        at com.google.android.gms.internal.firebase_ml.zzqz.zzf(com.google.firebase:firebase-ml-common@@22.1.2:53)
        at com.google.android.gms.internal.firebase_ml.zzqz$zza.zzoz(com.google.firebase:firebase-ml-common@@22.1.2:7)
        at com.google.android.gms.internal.firebase_ml.zzqz$zza.call(com.google.firebase:firebase-ml-common@@22.1.2:24)
        at com.google.android.gms.internal.firebase_ml.zzqf.zza(com.google.firebase:firebase-ml-common@@22.1.2:32)
        at com.google.android.gms.internal.firebase_ml.zzqe.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**To Reproduce**
Literally try to use library

My gradle
```


apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'io.sentry.android.gradle'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: "androidx.navigation.safeargs.kotlin"

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"
    defaultConfig {
        applicationId "com.p1ng2win.gabiapplication"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 68 //56
        versionName "1.820" //1.81
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false

            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }

    packagingOptions {
        exclude 'META-INF/atomicfu.kotlin_module'
    }
}

androidExtensions {
    experimental = true
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.google.android.material:material:1.2.1'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'androidx.preference:preference-ktx:1.1.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.1'

    //arch
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$ktx_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$ktx_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$ktx_version"
    implementation "androidx.fragment:fragment-ktx:1.2.5"

    //navigation
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    //testing
    testImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    //GooglePlay
    implementation 'com.google.android.play:core:1.8.3'
    implementation 'com.google.android.play:core-ktx:1.8.1'
    implementation 'com.google.android.gms:play-services-vision:20.1.2'

    //Firebase
    implementation platform('com.google.firebase:firebase-bom:26.1.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-perf-ktx'

    //LiveData, ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"

    //Sentry (crash analytics)
    implementation 'io.sentry:sentry-android:3.1.0'

    //Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.0'

    //Glide
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    kapt 'com.github.bumptech.glide:compiler:4.11.0'

    //BarcodeScanner
    implementation 'uk.co.brightec.kbarcode:kbarcode:1.2.2'
    implementation('com.journeyapps:zxing-android-embedded:4.1.0') { transitive = false }
    implementation 'com.google.zxing:core:3.3.0'

    //LeakCanary
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.2'

    //WebSocket
    implementation 'tech.gusavila92:java-android-websocket-client:1.2.2'

    //Grant Runtime Permission
    implementation 'com.androidisland.ezpermission:ezpermission:0.1.4'

    //SegmentedControl Button
    implementation 'com.github.trinnguyen:Android-SegmentView:master-SNAPSHOT'

    //Notification Builder
    implementation "io.karn:notify:1.3.0"

    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    kapt "androidx.room:room-compiler:$room_version"

    //KotlinX DateTime
    implementation "org.jetbrains.kotlinx:kotlinx-datetime:0.1.0"

    //Timber (logs)
    implementation 'com.jakewharton.timber:timber:4.7.1'

    //AdapterDelegates
    implementation 'com.hannesdorfmann:adapterdelegates4-kotlin-dsl:4.3.0'
    implementation 'com.hannesdorfmann:adapterdelegates4-kotlin-dsl-layoutcontainer:4.3.0'

}

```

**Smartphone (please complete the following information):**
 - Device: Xiaomi mi 9t
 - OS: MIUI 11
 - Version kbarcode:1.2.2

**Additional context**
I think you should migrate to google ml kit because firebase ml kit was deprecated

**Comment by PikalovPavel** [comment]
I have same issue

**Comment by alistairsykes** [comment]
We have updated a bunch of our dependencies so hopefully that will resolve your issue. 

Will be included in the next release.
